#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

COMMON_PATH := device/xiaomi/certus-common

# Architecture
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53

# Audio
USE_XML_AUDIO_POLICY_CONF := 1

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(COMMON_PATH)/bluetooth
BOARD_HAVE_BLUETOOTH := true

# Blur
TARGET_USES_BLUR := true

# Board
TARGET_BOARD_PLATFORM := mt6765

# Broken
BUILD_BROKEN_DUP_RULES := true

# Charger
BOARD_CHARGER_ENABLE_SUSPEND := true

# Display
TARGET_SCREEN_DENSITY := 320

# HIDL
DEVICE_MANIFEST_FILE := $(COMMON_PATH)/manifest.xml

# Init
TARGET_INIT_VENDOR_LIB := //$(COMMON_PATH):libinit_certus

# Kernel
BOARD_MKBOOTIMG_ARGS += --board $(TARGET_BOARD_PLATFORM) --header_version 1 --pagesize 2048
BOARD_KERNEL_CMDLINE += androidboot.boot_devices=bootdevice androidboot.selinux=permissive
TARGET_KERNEL_SOURCE := kernel/xiaomi/mt6765
TARGET_KERNEL_CONFIG := certus_defconfig

# OTA
TARGET_OTA_ASSERT_DEVICE := cactus,cereus,certus,certus64

# Partitons
ifeq ($(PRODUCT_USE_DYNAMIC_PARTITIONS),true)
BOARD_CERTUS_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor
BOARD_SUPER_PARTITION_BLOCK_DEVICES := cust vendor system
BOARD_SUPER_PARTITION_GROUPS := certus_dynamic_partitions
BOARD_SUPER_PARTITION_SYSTEM_DEVICE_SIZE := 2684354560
BOARD_SUPER_PARTITION_VENDOR_DEVICE_SIZE := 805306368
BOARD_SUPER_PARTITION_CUST_DEVICE_SIZE := 536870912
BOARD_CERTUS_DYNAMIC_PARTITIONS_SIZE := 4022337536
BOARD_SUPER_PARTITION_METADATA_DEVICE := system
BOARD_SUPER_PARTITION_SIZE := 4026531840
BOARD_USES_METADATA_PARTITION := true
else
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560
BOARD_VENDORIMAGE_PARTITION_SIZE := 805306368
endif

BOARD_USERDATAIMAGE_PARTITION_SIZE := 3221225472
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_FLASH_BLOCK_SIZE := 131072

# RIL
ENABLE_VENDOR_RIL_SERVICE := true
SIM_COUNT := 2

# Seccomp filters
BOARD_SECCOMP_POLICY := $(COMMON_PATH)/seccomp

# Sepolicy
ifeq ($(PRODUCT_USE_DYNAMIC_PARTITIONS),true)
BOARD_SEPOLICY_DIRS += $(COMMON_PATH)/sepolicy-dynamic/vendor
endif

# Vendor
VENDOR_SECURITY_PATCH := 2020-10-05
TARGET_COPY_OUT_VENDOR := vendor
BOARD_VNDK_VERSION := current

# Verified Boot
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Wi-Fi
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_STATE_CTRL_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_PARAM := "/dev/wmtWifi"
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
WIFI_DRIVER_FW_PATH_STA := STA
WIFI_DRIVER_FW_PATH_P2P := P2P
BOARD_WLAN_DEVICE := MediaTek
WIFI_DRIVER_FW_PATH_AP := AP
WIFI_DRIVER_STATE_OFF := 0
WIFI_DRIVER_STATE_ON := 1
